In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## Sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
# Define the vocabulary size
voc_size = 10000

In [4]:
## One Hot Representation

one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[7624, 5437, 2324, 3116],
 [7624, 5437, 2324, 8289],
 [7624, 4557, 2324, 6078],
 [9265, 8503, 8358, 5575, 7576],
 [9265, 8503, 8358, 5575, 5659],
 [7202, 7624, 9442, 2324, 4344],
 [2389, 1533, 3542, 5575]]

In [5]:
# Word Embedding Representation 

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [6]:
sent_length=8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 7624, 5437, 2324, 3116],
       [   0,    0,    0,    0, 7624, 5437, 2324, 8289],
       [   0,    0,    0,    0, 7624, 4557, 2324, 6078],
       [   0,    0,    0, 9265, 8503, 8358, 5575, 7576],
       [   0,    0,    0, 9265, 8503, 8358, 5575, 5659],
       [   0,    0,    0, 7202, 7624, 9442, 2324, 4344],
       [   0,    0,    0,    0, 2389, 1533, 3542, 5575]], dtype=int32)

In [7]:
# Feature representation
dim = 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.build(input_shape=(None, sent_length))  # Ensure the model is built
model.compile(optimizer='adam', loss='mse')

In [13]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step


array([[[ 0.02420951, -0.01847734, -0.01040276, -0.01195228,
          0.02066698, -0.03643196, -0.00038525,  0.04563895,
          0.04558391, -0.03364717],
        [ 0.02420951, -0.01847734, -0.01040276, -0.01195228,
          0.02066698, -0.03643196, -0.00038525,  0.04563895,
          0.04558391, -0.03364717],
        [ 0.02420951, -0.01847734, -0.01040276, -0.01195228,
          0.02066698, -0.03643196, -0.00038525,  0.04563895,
          0.04558391, -0.03364717],
        [ 0.02420951, -0.01847734, -0.01040276, -0.01195228,
          0.02066698, -0.03643196, -0.00038525,  0.04563895,
          0.04558391, -0.03364717],
        [-0.00808864, -0.03158323, -0.04965559,  0.0037608 ,
          0.02813169, -0.00628825, -0.02884576, -0.04032988,
         -0.00691023, -0.0353734 ],
        [-0.04604442,  0.01472331, -0.01403608,  0.03741615,
         -0.03691442,  0.03913411,  0.01532965, -0.02583239,
         -0.02681126, -0.01509203],
        [-0.03395184, -0.0331016 , -0.03652632,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 7624, 5437, 2324, 3116], dtype=int32)

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[[ 0.02420951, -0.01847734, -0.01040276, -0.01195228,
          0.02066698, -0.03643196, -0.00038525,  0.04563895,
          0.04558391, -0.03364717],
        [ 0.02420951, -0.01847734, -0.01040276, -0.01195228,
          0.02066698, -0.03643196, -0.00038525,  0.04563895,
          0.04558391, -0.03364717],
        [ 0.02420951, -0.01847734, -0.01040276, -0.01195228,
          0.02066698, -0.03643196, -0.00038525,  0.04563895,
          0.04558391, -0.03364717],
        [ 0.02420951, -0.01847734, -0.01040276, -0.01195228,
          0.02066698, -0.03643196, -0.00038525,  0.04563895,
          0.04558391, -0.03364717],
        [-0.00808864, -0.03158323, -0.04965559,  0.0037608 ,
          0.02813169, -0.00628825, -0.02884576, -0.04032988,
         -0.00691023, -0.0353734 ],
        [-0.04604442,  0.01472331, -0.01403608,  0.03741615,
         -0.03691442,  0.03913411,  0.01532965, -0.02583239,
         -0.02681126, -0.01509203],
        [-0.03395184, -0.0331016 , -0.03652632,  0.0